<?php
$data = array (
  150 => 
  array (
    'cat_id' => '150',
    'cat_name' => '黄金白银',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '150',
    'name' => '黄金白银',
  ),
  291 => 
  array (
    'cat_id' => '291',
    'cat_name' => '足金',
    'measure_unit' => '',
    'parent_id' => '150',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 17,
    'level' => 1,
    'id' => '291',
    'name' => '足金',
  ),
  363 => 
  array (
    'cat_id' => '363',
    'cat_name' => '白银',
    'measure_unit' => '',
    'parent_id' => '150',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '363',
    'name' => '白银',
  ),
  368 => 
  array (
    'cat_id' => '368',
    'cat_name' => '铂金',
    'measure_unit' => '',
    'parent_id' => '150',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '368',
    'name' => '铂金',
  ),
  361 => 
  array (
    'cat_id' => '361',
    'cat_name' => 'k金',
    'measure_unit' => '',
    'parent_id' => '150',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '361',
    'name' => 'k金',
  ),
  362 => 
  array (
    'cat_id' => '362',
    'cat_name' => '钯金',
    'measure_unit' => '',
    'parent_id' => '150',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '362',
    'name' => '钯金',
  ),
  272 => 
  array (
    'cat_id' => '272',
    'cat_name' => '钻石珠宝',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => '4',
    'level' => 0,
    'id' => '272',
    'name' => '钻石珠宝',
  ),
  346 => 
  array (
    'cat_id' => '346',
    'cat_name' => '戒指',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 10,
    'level' => 1,
    'id' => '346',
    'name' => '戒指',
  ),
  380 => 
  array (
    'cat_id' => '380',
    'cat_name' => '耳饰',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '380',
    'name' => '耳饰',
  ),
  367 => 
  array (
    'cat_id' => '367',
    'cat_name' => '吊坠',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '367',
    'name' => '吊坠',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '大牌名包',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '3',
    'has_children' => '4',
    'goods_num' => '9',
    'level' => 0,
    'id' => '18',
    'name' => '大牌名包',
  ),
  384 => 
  array (
    'cat_id' => '384',
    'cat_name' => '路易.威登',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '384',
    'name' => '路易.威登',
  ),
  383 => 
  array (
    'cat_id' => '383',
    'cat_name' => '香奈儿',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '383',
    'name' => '香奈儿',
  ),
  390 => 
  array (
    'cat_id' => '390',
    'cat_name' => '品牌',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '390',
    'name' => '品牌',
  ),
  370 => 
  array (
    'cat_id' => '370',
    'cat_name' => '爱马仕',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '370',
    'name' => '爱马仕',
  ),
  352 => 
  array (
    'cat_id' => '352',
    'cat_name' => '高端腕表',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '4',
    'has_children' => '4',
    'goods_num' => '6',
    'level' => 0,
    'id' => '352',
    'name' => '高端腕表',
  ),
  371 => 
  array (
    'cat_id' => '371',
    'cat_name' => '劳力士',
    'measure_unit' => '',
    'parent_id' => '352',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '371',
    'name' => '劳力士',
  ),
  379 => 
  array (
    'cat_id' => '379',
    'cat_name' => '百达翡丽',
    'measure_unit' => '',
    'parent_id' => '352',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '379',
    'name' => '百达翡丽',
  ),
  372 => 
  array (
    'cat_id' => '372',
    'cat_name' => '欧米茄',
    'measure_unit' => '',
    'parent_id' => '352',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '372',
    'name' => '欧米茄',
  ),
  385 => 
  array (
    'cat_id' => '385',
    'cat_name' => '浪琴',
    'measure_unit' => '',
    'parent_id' => '352',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '385',
    'name' => '浪琴',
  ),
  292 => 
  array (
    'cat_id' => '292',
    'cat_name' => '手机数码',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '5',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '292',
    'name' => '手机数码',
  ),
  347 => 
  array (
    'cat_id' => '347',
    'cat_name' => '手机',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '49',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '347',
    'name' => '手机',
  ),
  348 => 
  array (
    'cat_id' => '348',
    'cat_name' => '相机',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '348',
    'name' => '相机',
  ),
  349 => 
  array (
    'cat_id' => '349',
    'cat_name' => '电脑',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '349',
    'name' => '电脑',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '玉石文玩',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '4',
    'goods_num' => '4',
    'level' => 0,
    'id' => '16',
    'name' => '玉石文玩',
  ),
  358 => 
  array (
    'cat_id' => '358',
    'cat_name' => '和田玉',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 11,
    'level' => 1,
    'id' => '358',
    'name' => '和田玉',
  ),
  359 => 
  array (
    'cat_id' => '359',
    'cat_name' => '翡翠',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '359',
    'name' => '翡翠',
  ),
  360 => 
  array (
    'cat_id' => '360',
    'cat_name' => '蜜蜡',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '360',
    'name' => '蜜蜡',
  ),
  365 => 
  array (
    'cat_id' => '365',
    'cat_name' => '小叶紫檀',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '365',
    'name' => '小叶紫檀',
  ),
  148 => 
  array (
    'cat_id' => '148',
    'cat_name' => '礼品购物卡',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '7',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '148',
    'name' => '礼品购物卡',
  ),
  378 => 
  array (
    'cat_id' => '378',
    'cat_name' => '乐天玛特',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '378',
    'name' => '乐天玛特',
  ),
  399 => 
  array (
    'cat_id' => '399',
    'cat_name' => '家乐福',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '399',
    'name' => '家乐福',
  ),
  376 => 
  array (
    'cat_id' => '376',
    'cat_name' => '美罗',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '376',
    'name' => '美罗',
  ),
  377 => 
  array (
    'cat_id' => '377',
    'cat_name' => '大润发',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '377',
    'name' => '大润发',
  ),
  398 => 
  array (
    'cat_id' => '398',
    'cat_name' => '欧尚',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '398',
    'name' => '欧尚',
  ),
);
?>