<?php
$data = array (
  0 => 
  array (
    'cat_id' => '150',
    'cat_name' => '黄金白银',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '272',
    'cat_name' => '钻石珠宝',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => '4',
  ),
  2 => 
  array (
    'cat_id' => '18',
    'cat_name' => '大牌名包',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '3',
    'has_children' => '4',
    'goods_num' => '9',
  ),
  3 => 
  array (
    'cat_id' => '352',
    'cat_name' => '高端腕表',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '4',
    'has_children' => '4',
    'goods_num' => '6',
  ),
  4 => 
  array (
    'cat_id' => '292',
    'cat_name' => '手机数码',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '5',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '16',
    'cat_name' => '玉石文玩',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '4',
    'goods_num' => '4',
  ),
  6 => 
  array (
    'cat_id' => '148',
    'cat_name' => '礼品购物卡',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '7',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '358',
    'cat_name' => '和田玉',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 11,
  ),
  8 => 
  array (
    'cat_id' => '359',
    'cat_name' => '翡翠',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  9 => 
  array (
    'cat_id' => '360',
    'cat_name' => '蜜蜡',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '365',
    'cat_name' => '小叶紫檀',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '384',
    'cat_name' => '路易.威登',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '383',
    'cat_name' => '香奈儿',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '390',
    'cat_name' => '品牌',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '370',
    'cat_name' => '爱马仕',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  15 => 
  array (
    'cat_id' => '378',
    'cat_name' => '乐天玛特',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  16 => 
  array (
    'cat_id' => '399',
    'cat_name' => '家乐福',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '376',
    'cat_name' => '美罗',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  18 => 
  array (
    'cat_id' => '377',
    'cat_name' => '大润发',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  19 => 
  array (
    'cat_id' => '398',
    'cat_name' => '欧尚',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '291',
    'cat_name' => '足金',
    'measure_unit' => '',
    'parent_id' => '150',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 17,
  ),
  21 => 
  array (
    'cat_id' => '363',
    'cat_name' => '白银',
    'measure_unit' => '',
    'parent_id' => '150',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  22 => 
  array (
    'cat_id' => '368',
    'cat_name' => '铂金',
    'measure_unit' => '',
    'parent_id' => '150',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '361',
    'cat_name' => 'k金',
    'measure_unit' => '',
    'parent_id' => '150',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '362',
    'cat_name' => '钯金',
    'measure_unit' => '',
    'parent_id' => '150',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '346',
    'cat_name' => '戒指',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 10,
  ),
  26 => 
  array (
    'cat_id' => '380',
    'cat_name' => '耳饰',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  27 => 
  array (
    'cat_id' => '367',
    'cat_name' => '吊坠',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  28 => 
  array (
    'cat_id' => '347',
    'cat_name' => '手机',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '49',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  29 => 
  array (
    'cat_id' => '348',
    'cat_name' => '相机',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  30 => 
  array (
    'cat_id' => '349',
    'cat_name' => '电脑',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  31 => 
  array (
    'cat_id' => '371',
    'cat_name' => '劳力士',
    'measure_unit' => '',
    'parent_id' => '352',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  32 => 
  array (
    'cat_id' => '379',
    'cat_name' => '百达翡丽',
    'measure_unit' => '',
    'parent_id' => '352',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  33 => 
  array (
    'cat_id' => '372',
    'cat_name' => '欧米茄',
    'measure_unit' => '',
    'parent_id' => '352',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  34 => 
  array (
    'cat_id' => '385',
    'cat_name' => '浪琴',
    'measure_unit' => '',
    'parent_id' => '352',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>